Create two random 3D arrays, at least 3x3x3 in size. The first should have random integers between 0 and 100, while the second should contain floating points numbers drawn from the normal distribution, with mean -1 and standard deviation of 2

What are the default datatypes of integer and floating-point arrays in NumPy?

In [15]:
import numpy as np
low = 0
high = 10
size = 1, 2, 3
array_1 = np.random.randint(low, high, size)
print(array_1)
print(np.mean(array_1, axis=0))
print(np.mean(array_1, axis=1))
print(np.mean(array_1, axis=2))
array_1.dtype
array_2 = np.random.randn(*size) * 2 - 1
array_2

[[[9 8 5]
  [9 0 4]]]
[[9. 8. 5.]
 [9. 0. 4.]]
[[9.  4.  4.5]]
[[7.33333333 4.33333333]]


array([[[-3.63562438, -1.77063624, -1.33167038],
        [-4.14833071, -0.97586423,  0.5258932 ]]])

2. Center the distribution of the first integer array around 0, with minimal and maximal values ranging between -1 and 1.

In [ ]:
middle = (array_1.max() - array_1.min()) / 2
centered_array_1 = (array_1 - middle) / middle
centered_array_1

3. Calculate the mean and standard deviation of each array along the last axis, and the sum along the second axis. Use the object-oriented implementation of these functions.